name: sih
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3
  provider: ^6.1.2
  location: ^5.0.0
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  latlong2: ^0.9.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.5.1
  timezone: ^0.10.0
  uuid: ^4.5.1
  app_settings: ^5.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/background.png
    - assets/home.png
    - assets/driver_signup.png
    - assets/user_home.png
    - assets/user_report.png
    - assets/ur.png
    - assets/route.png
    - assets/profile.jpg
    - assets/buses.json
    - assets/buslocations.json
    - assets/routes.json
    - assets/schedule.json
    - assets/stops.json
    - assets/gift.png
    - assets/Animation.json
    - assets/headerlogo.png
    - assets/animation1.json
    - assets/404notfound.json
    - assets/animation2.json
